backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/content/team'
    create: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'string' }
