site:
  name: 3c
  site: 'https://wendemo.netlify.app/'
  base: '/'
  trailingSlash: false

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
