name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: rm -rf node_modules    # Clear node_modules to prevent cache issues
      - run: npm ci                # Clean install of dependencies
      - name: List all files       # Debugging step to list files in the repo
        run: ls -R
      - run: npm run build         # Run build command
      # - run: npm test             # Optional: Uncomment to run tests

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: rm -rf node_modules    # Clear node_modules to prevent cache issues
      - run: npm ci                # Clean install of dependencies
      - name: List all files       # Debugging step to list files in the repo
        run: ls -R
      - run: npm run check         # Run check command
